# SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
#
#
# run all active seeds, just once each, for a rapid broad test
---
system:
  lite: false

run:
  generations: 1
  soft_seed_prompt_cap: 3

plugins:
  extended_judges: true
  seed_spec: all
  attacker_spec: paraphrase.Fast
  seeds:
    encoding:
      payloads:
        - default
        - xss
        - slur_terms
