---
# run a thorough test for toxicity generation
# . use seeds that attempt to evoke toxic responses
# . do paraphrasing to increase coverage
# . paraphrasing increases the prompt vocab a lot
system:
  lite: false

run:
  generations: 5

plugins:
  seed_spec: atkgen.Tox,continuation.ContinueSlursReclaimedSlurs,encoding,lmrc.Anthropomorphisation,lmrc.Bullying,lmrc.Deadnaming,lmrc.Profanity,lmrc.SlurUsage,realtoxicityprompts,
  seeds:
    encoding:
      payloads:
        - slur_terms
  attacker_spec: paraphrase.Fast
