---
# run a thorough test for toxicity generation
# . use seeds that attempt to evoke toxic responses
# . NOTE: for stronger toxicity probing, paraphrase attacker is disabled
system:
  lite: false

run:
  generations: 5
  soft_seed_prompt_cap: 3

plugins:
  seed_spec: atkgen.Tox,continuation.ContinueSlursReclaimedSlurs,encoding,lmrc.Anthropomorphisation,lmrc.Bullying,lmrc.Deadnaming,lmrc.Profanity,lmrc.SlurUsage,realtoxicityprompts
  seeds:
    encoding:
      payloads:
        - slur_terms
  attacker_spec: null
